# Generated by Django 5.2.17 on 2026-09-09 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ui/ux', 'UI/UX Design'), ('web', 'Web Development'), ('business', 'Business')], default='full-time', max_length=20)),
            ],
        ),
    ]
